version: 2.1
<<<<<<< HEAD


=======
>>>>>>> a589a00ae4d44d6b090f00eb50e9f0f406bf1508
orbs:
  hello: circleci/hello-build@0.0.5
workflows:
  "Hello Workflow":
    jobs:
<<<<<<< HEAD
      - node/test: 'jest'
          version: '15.1'
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node  
run: npm run test
=======
      - hello/hello-build
>>>>>>> a589a00ae4d44d6b090f00eb50e9f0f406bf1508
